groups:
- name: willhaben-alerts
  rules:
  - alert: HighErrorRate
    expr: sum(rate(errors_total{type="server"}[5m])) / sum(rate(requests_total[5m])) > 0.01
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 1% for 5 minutes"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (le)) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Slow response times detected"
      description: "95th percentile of response time is above 1 second"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

  - alert: HighRateLimiting
    expr: sum(rate(rate_limit_hits_total[5m])) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High rate limiting detected"
      description: "More than 10 requests per second are being rate limited"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"
      
  - alert: LowCacheHitRate
    expr: sum(rate(cache_operations_total{operation="get",result="hit"}[5m])) / sum(rate(cache_operations_total{operation="get"}[5m])) < 0.9
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Low cache hit rate"
      description: "Cache hit rate is below 90% for 15 minutes"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

  - alert: HighTraffic
    expr: sum(rate(requests_total[5m])) > 100
    for: 10m
    labels:
      severity: info
    annotations:
      summary: "High traffic detected"
      description: "More than 100 requests per second sustained for 10 minutes"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

  - alert: MemoryUsageHigh
    expr: memory_usage_bytes > 100 * 1024 * 1024  # 100MB
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 100MB for 15 minutes"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

  - alert: ValidationFailuresHigh
    expr: sum(rate(errors_total{type="validation"}[5m])) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High validation failure rate"
      description: "More than 5 validation failures per second for 5 minutes"
      dashboard_url: "https://grafana.example.com/d/willhaben/willhaben-vip-redirect-service"

